import Foundation
struct UserDetailsInformation : Codable {
	let city : String
	let addressBuild : String
	let contractId : String
	let etazh : Int
	let __Olt : String
	let addressDistrict : String
	let pasportDate : String
	let birthDate : String
	let pasportNum : String
	let phone : String
	let pasportGrant : String
	let total : Int
	let addressFlat : String
	let addressStreetTypeName : String
	let addressStreet2 : String
	let locationId : Int
	let uid : Int
	let _PortOnu : String
	let taxNumber : String
	let countryId : Int
	let zip : String
	let _Port : Int
	let _MacOnu : String
	let coordx : Int
	let affected : Int
	let email : String
	let fio2 : String
	let entrance : Int
	let fio3 : String
	let floor : Int
	let addressStreet : String
	let cableLength : Int
	let addressFull : String
	let fio : String
	let podezd : Int
	let cableOwnerId : Int
	let list : [String]
	let phoneSms : String
	let comments : String
	let contractDate : String
	let streetId : Int
	let districtId : Int
	let _AkciyaId : Int
	let acceptRules : Int
	let contractSufix : String

	enum CodingKeys: String, CodingKey {

		case city = "city"
		case addressBuild = "addressBuild"
		case contractId = "contractId"
		case etazh = "etazh"
		case __Olt = "__Olt"
		case addressDistrict = "addressDistrict"
		case pasportDate = "pasportDate"
		case birthDate = "birthDate"
		case pasportNum = "pasportNum"
		case phone = "phone"
		case pasportGrant = "pasportGrant"
		case total = "total"
		case addressFlat = "addressFlat"
		case addressStreetTypeName = "addressStreetTypeName"
		case addressStreet2 = "addressStreet2"
		case locationId = "locationId"
		case uid = "uid"
		case _PortOnu = "_PortOnu"
		case taxNumber = "taxNumber"
		case countryId = "countryId"
		case zip = "zip"
		case _Port = "_Port"
		case _MacOnu = "_MacOnu"
		case coordx = "coordx"
		case affected = "affected"
		case email = "email"
		case fio2 = "fio2"
		case entrance = "entrance"
		case fio3 = "fio3"
		case floor = "floor"
		case addressStreet = "addressStreet"
		case cableLength = "cableLength"
		case addressFull = "addressFull"
		case fio = "fio"
		case podezd = "podezd"
		case cableOwnerId = "cableOwnerId"
		case list = "list"
		case phoneSms = "phoneSms"
		case comments = "comments"
		case contractDate = "contractDate"
		case streetId = "streetId"
		case districtId = "districtId"
		case _AkciyaId = "_AkciyaId"
		case acceptRules = "acceptRules"
		case contractSufix = "contractSufix"
	}

}
